name: binder_conda_env
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=4.2.5
  - jupyter-collaboration=3.0.0b3
  - nb_conda
  - tectonic
  - pip
  - pip:
    - nbgitpuller
    - tectonic